### ISSUE TITLE
代码一毛一样为什么会出现 ValueError: Input 0 is incompatible with layer Normal: expected ndim=3, found ndim=2 这样的错误呢?

### ISSUE THREAD

**Issue by 1148330040** [CyberZHG/keras-xlnet#23]
您好首先非常感谢您提供的这个项目, 让我可以轻易的使用xlnet, 我在上周使用同样的代码都没有任何问题, 但是今天当我重新测试的时候就出现了下面的报错, 请问是为什么呢?

model = load_trained_model_from_checkpoint(
    config_path=paths.config,
    checkpoint_path=paths.model,
    batch_size=BATCH_SIZE,
    memory_len=0,
    target_len=SEQ_LEN,
    in_train_phase=False,
    attention_type=ATTENTION_TYPE_BI,
)

# 加载预训练权重
last = model.output
extract = Extract(index=-1, name='Extract')(last)
dense = keras.layers.Dense(units=768, name='Dense')(extract)
norm = keras.layers.BatchNormalization(name='Normal')(dense)
output = keras.layers.Dense(units=2, activation='softmax', name='Softmax')(norm)
model = keras.models.Model(inputs=model.inputs, outputs=output)
这是报错:
Traceback (most recent call last):
  File "D:/project/nlp_label_processing/Xlnet_test.py", line 245, in <module>
    norm = keras.layers.BatchNormalization(name='Normal')(dense)
  File "C:\Users\tzl17\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "C:\Users\tzl17\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 472, in __call__
    self.assert_input_compatibility(inputs)
  File "C:\Users\tzl17\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 342, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer Normal: expected ndim=3, found ndim=2

Process finished with exit code 1
提示形状不同, 我查看了层之后, 在dense后面增加了一行代码:
dense = keras.layers.Reshape((30, 768))(dense)
我查看了层之后, 发现很奇怪的现象:
__________________________________________________________________________________________________
Extract (Extract)               (None, 30, 768)      0           FeedForward-Normal-12[0][0]      
__________________________________________________________________________________________________
Dense (Dense)                   (None, 30, 768)      590592      Extract[0][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 30, 768)      0           Dense[0][0]                      
__________________________________________________________________________________________________
Normal (BatchNormalization)     (None, 30, 768)      3072        reshape_1[0][0]                  
__________________________________________________________________________________________________
Softmax (Dense)                 (None, 30, 2)        1538        Normal[0][0]                     
===================================================================================它并不是None, 768->None, 2而是多出来来了个30, 我设置了每一行文本填充长度为30, 因此这种情况是不是意味着以每个单词为维度, 生成了768个编码? 由于上周我并没有在成功之后检查model.summary() 因此我不确定是不是我的模型除了问题.
由于层是以(None, 30, 768)的形式出现, 显然我的数据输入进去的时候报了错.
因此我希望能获取您的帮助, 求您解惑!!

**Comment by 1148330040** [comment]
"ERROR: bert4keras 0.8.7 has requirement keras<=2.3.1, but you'll have keras 2.4.3 which is incompatible."
"ERROR: keras-bert 0.86.0 has requirement Keras>=2.4.3, but you'll have keras 2.3.1 which is incompatible."
两者之间出现了冲突. 导致keras的版本无法满足keras-bert因此层与层之间的衔接问题出现了错误

**Comment by 1148330040** [comment]
这个问题是因为我在使用bert4keras时，它将keras的版本限制到了2.3.1但是在bert-keras中要求的版本是2.4.3因此发生了冲突



---原始邮件---
发件人: "stale[bot]"<notifications@github.com&gt;
发送时间: 2020年9月20日(周日) 上午7:02
收件人: "CyberZHG/keras-xlnet"<keras-xlnet@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"oldpotatoes"<1148330040@qq.com&gt;;
主题: Re: [CyberZHG/keras-xlnet] 代码一毛一样为什么会出现 ValueError: Input 0 is incompatible with layer Normal: expected ndim=3, found ndim=2 这样的错误呢? (#23)




 
Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
 
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
